{
  "media_svr_id":126,
  "tenant_name":"绿地全球商品优选",
  "logo_picture":"http://wx.qlogo.cn/mmopen/DuPxrndJiaDp8oRuMZCKIg9lyPGuB3glibjbc3ILxVPRQhq9iaeyOkfExA6WEzoTs16Pdrfs9bSicqvCuHOoCDGshBoIib7ylbC3V/0",
  "title":"616",
  "color":"Color010",
  "canuse_time_interval":"周一至周日",
  "use_instructions":"666",
  "discount_description":"凭此券消费打8折；适用于fruits；不适用于closes；不可与其他优惠共享",
  "face_value":80,
  "get_mode":2,
  "stock_qty":"10",
  "qbarcode_channel":1,
  "status":"Y",
  "limit_usr_number":"6",
  "coupontype":"0",
  "data_json":"{\
    "card\":{\
      "card_type\":\"DISCOUNT\",\
      "discount\":{\
        "base_info\":{\
          "logo_url\":\"http://wx.qlogo.cn/mmopen/DuPxrndJiaDp8oRuMZCKIg9lyPGuB3glibjbc3ILxVPRQhq9iaeyOkfExA6WEzoTs16Pdrfs9bSicqvCuHOoCDGshBoIib7ylbC3V/0\",\
          "code_type\":\"CODE_TYPE_QRCODE\",\
          "brand_name\":\"绿地全球商品优选\",\
          "title\":\"616\",\
          "color\":\"Color010\",\
          "notice\":\"\",\
          "description\":\"666\",\
          "sku\":{\"quantity\":\"10\"},\
          "date_info\":{\
            "type\":\"DATE_TYPE_FIX_TIME_RANGE\",\
            "begin_timestamp\":1528041600,\
            "end_timestamp\":1529510399},\
            "use_all_locations\":true,\
            "get_limit\":\"6\",\
            "can_share\":true,\
            "can_give_friend\":true,\
            "use_custom_code\":false},\
            "advanced_info\":{\
              "use_condition\":{\
                "accept_category\":\"fruits\",\
                "reject_category\":\"closes\",\
                "can_use_with_other_discount\":false},\
                "time_limit\":[{\
                  "type\":\"MONDAY\"},{\
                  "type\":\"TUESDAY\"},{\
                  "type\":\"WEDNESDAY\"},{\
                  "type\":\"THURSDAY\"},{\
                  "type\":\"FRIDAY\"},{\
                  "type\":\"SATURDAY\"},{\
                  "type\":\"SUNDAY\"}]},\
                  "discount\":20}}}",
                  "datajson_edit":"{\
                    "card_id\":\"wx_card_no\",\
                    "discount\":{\
                      "base_info\":{\
                        "logo_url\":\"http://wx.qlogo.cn/mmopen/DuPxrndJiaDp8oRuMZCKIg9lyPGuB3glibjbc3ILxVPRQhq9iaeyOkfExA6WEzoTs16Pdrfs9bSicqvCuHOoCDGshBoIib7ylbC3V/0\",\
                        "code_type\":\"CODE_TYPE_QRCODE\",\
                        "color\":\"Color010\",\
                        "notice\":\"\",\
                        "description\":\"666\",\
                        "date_info\":{\
                          "type\":\"DATE_TYPE_FIX_TIME_RANGE\",\
                          "begin_timestamp\":1528041600,\
                          "end_timestamp\":1529510399},\
                          "use_all_locations\":true,\
                          "get_limit\":\"6\",\
                          "can_share\":true,\
                          "can_give_friend\":true},\
                          "advanced_info\":{\
                            "time_limit\":[{\
                            "type\":\"MONDAY\"},{\
                            "type\":\"TUESDAY\"},{\
                            "type\":\"WEDNESDAY\"},{\
                            "type\":\"THURSDAY\"},{\
                            "type\":\"FRIDAY\"},{\
                            "type\":\"SATURDAY\"},{\
                            "type\":\"SUNDAY\"}]}}}",
                          "isallmarket":"Y",
                          "use_begin_date":"2018-06-03T16:00:00.000Z",
                          "use_begin_end":"2018-06-20T15:59:59.000Z"}
